"""add sanitization provenance to resume versions

Revision ID: dd2329f32308
Revises: 3b8b551883d8
Create Date: 2026-07-30 21:06:41.154308+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "dd2329f32308"
down_revision: str | None = "3b8b551883d8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply this revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "resume_versions",
        sa.Column("sanitization_report", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    )
    op.add_column("resume_versions", sa.Column("injection_risk_score", sa.Float(), nullable=False))
    op.add_column("resume_versions", sa.Column("quarantined", sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert this revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("resume_versions", "quarantined")
    op.drop_column("resume_versions", "injection_risk_score")
    op.drop_column("resume_versions", "sanitization_report")
    # ### end Alembic commands ###
